### ISSUE TITLE
Test failed in master

### ISSUE THREAD

**Issue by shalugin** [vt-middleware/passay#65]
Maven log:

```
TernaryTreeDictionary time to construct: 1580ms
TernaryTreeDictionary search time: 19ms
TernaryTreeDictionary avg time per search: 1908ns
[ERROR] Tests run: 21114, Failures: 2, Errors: 0, Skipped: 1, Time elapsed: 85.636 s <<< FAILURE! - in TestSuite
[ERROR] checkPassword(org.passay.WhitespaceRuleTest)  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>

[ERROR] testSpringWiring(org.passay.spring.SpringTest)  Time elapsed: 21.818 s  <<< FAILURE!
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 6 in XML document from class path resource [spring-context.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 115; cvc-elt.1: Cannot find the declaration of element 'beans'.
        at org.passay.spring.SpringTest.testSpringWiring(SpringTest.java:32)
Caused by: org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'beans'.
        at org.passay.spring.SpringTest.testSpringWiring(SpringTest.java:32)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] org.passay.WhitespaceRuleTest.checkPassword(org.passay.WhitespaceRuleTest)
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[ERROR]   Run 4: WhitespaceRuleTest>AbstractRuleTest.checkPassword:38 expected:<1> but was:<2>
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS
[INFO]   Run 7: PASS
[INFO]   Run 8: PASS
[INFO]
[ERROR]   SpringTest.testSpringWiring:32 ╗ XmlBeanDefinitionStore Line 6 in XML document...
[INFO]
[ERROR] Tests run: 21107, Failures: 2, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:36 min
[INFO] Finished at: 2017-10-24T17:52:08+03:00
[INFO] Final Memory: 29M/532M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project passay: There are test failures.
[ERROR]
[ERROR] Please refer to C:\temp\github\passay\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
```

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T22:39:06+03:00)
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_144\jre
Default locale: ru_RU, platform encoding: Cp1251
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by shalugin** [comment]
@dfish3r Every build.

One warning at build start:

```
[INFO] Scanning for projects...
[WARNING] The project org.passay:passay:jar:1.3.1-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
```

**Comment by serac** [comment]
The XML parsing error above could be caused by inability to load the XSD file at http://schema.spring.io/beans/spring-beans.xsd. Can you confirm you can fetch the file from your build host?

As for the WhitespaceRuleTest, I have a hunch what's happening. Here's the test data for the failed run:

        {
          new WhitespaceRule(),
          new PasswordData("AycDPs" + System.getProperty("line.separator") + "yz"),
          codes(WhitespaceRule.ERROR_CODE),
        },

The build host is Windows where I assume the `line.separator` is CRLF, so there are two whitespace characters in the password instead of two. That's arguably a cross-platform bug we should fix.

**Comment by shalugin** [comment]
I can fetch XSD file at http://schema.spring.io/beans/spring-beans.xsd. 

Yes, the problem in Windows line separator:

```
[
  ILLEGAL_WHITESPACE:{whitespaceCharacter=\n, matchBehavior=contains},
  ILLEGAL_WHITESPACE:{whitespaceCharacter=\r, matchBehavior=contains}
]
```

**Comment by dfish3r** [comment]
I believe I fixed the whitespace test failure.
Still not sure what's going on with the XSD error.

**Comment by shalugin** [comment]
Now it's fixed.

Build log:

```
[INFO] --- maven-assembly-plugin:3.1.0:single (assembly) @ passay ---
[INFO] Reading assembly descriptor: C:\temp\github\passay/src/main/assembly/passay.xml
[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /
[INFO] Building tar: C:\temp\github\passay\target\passay-1.3.1-SNAPSHOT-dist.tar.gz
[WARNING] Entry: passay-1.3.1-SNAPSHOT/src/test/java/org/passay/dictionary/MemoryMappedFileWordListDictionaryPerfTest.java longer than 100 characters.
[WARNING] Resulting tar file can only be processed successfully by GNU compatible tar commands
[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /
[INFO] Building zip: C:\temp\github\passay\target\passay-1.3.1-SNAPSHOT-dist.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:05 min
[INFO] Finished at: 2017-12-14T22:14:21+03:00
[INFO] Final Memory: 36M/722M
[INFO] ------------------------------------------------------------------------

```
